version: '2'
services:
    blip1-app:
        image: blip1
        external_links:
            - blip1-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/blip1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    blip1-mysql:
        extends:
            file: mysql.yml
            service: blip1-mysql
